### PR TITLE
Verify that all PRs are labeled with `bug`, `enhancement`, or `interface-change`

### PR DESCRIPTION
**Pull request by jesusvasquez333**
This PR solved #321.

It adds the GitHub actions [verify-pull-request-labels](https://github.com/marketplace/actions/verify-pull-request-labels) to verify that all PRs have at least one of these labels before they can be merged: `bug`, `enhancement`, `interface-change`.

This action works around the issue I mentioned in #321 regarding checks trigger with different conditions, and instead works in the following way:
- If a PR does not have one of the valid labels, then the Github check will succeed, but it will create a pull request review, requesting for changes. This will prevent the PR to be merge until the review is addressed. 
- If a PR have at least one valid label, then the Github check will also succeed, and it will create a pull request review, approving it. This will clear the review requesting for changes from a previous failed check. 
- The action will be triggered when a pull request is open, updated, and when labels are added/removed. 

As the Github Check alway succeed, we will not have the problem I mentioned in #321. Instead, the PR will be block using normal pull request workflow.

An example scenario is:
- A PR is open, without one of the mandatory labels. The action runs and creates a PR review, requesting for changes. This will prevent the PR to be merged.
- One of the mandatory labels is added to the PR. The action will be triggered again, and will create a new PR review, approving it. This will dismiss the previous request for changes. 
- If the label is removed, it will trigger the action again, and step 1 will happen again.
- If the PR labeled correctly before opening the PR, then the first action will just crate a PR review approving it.

So, in order for this new feature to work, we will need to increase the number of `Required approving reviewers` from `1` to `2`: one review will always come from this action, and the other review will be the one needed from a real reviewer.

This PR itself will be an example of how this feature works. I'm opening the PR without any label, in order to let the action to crate the PR review, request changes. Then I will add a correct label to fix it.

### CODE REVIEW

**Comment by jesusvasquez333** [comment]
At this point, the PR can not be merged, as there is a request for changes, indicating that a mandatory label is missing. 
I will add the label next.

**Comment by jesusvasquez333** [comment]
Now that I added a correct label, the PR can be merge normally. Increasing the `Required approving reviewers` to `2`, one more review will be needed, from one of us.

**Comment by eyyoung24** [comment]
Do we need to require 2 approvals to pass? github-actions[bot] will always pass (once we have the right tags). But I think we want to also have a human check it, right?

**Comment by eyyoung24** [comment]
Annotation 2020-03-20 104442

**Comment by eyyoung24** [comment]
You can see in the image above that we can already merge it even though no human has approved it.

**Comment by jesusvasquez333** [comment]
@eyyoung24 Yes, you are correct. I explained that in the description of this PR:

> So, in order for this new feature to work, we will need to increase the number of `Required approving reviewers` from `1` to `2`: one review will always come from this action, and the other review will be the one needed from a real reviewer.

**Pull request merged**
