### PR TITLE
Reorders imports in compliance with pep8.

### PR DESCRIPTION
**Pull request by swh76**
## Issue
This PR is required to issue resolve https://github.com/slaclab/pysmurf/issues/393.

## Description
Trivial reordering of python module imports throughout pysmurf, both client and core.  After merging this PR, we'll pass this check:

```
flake8 --import-order-style=pep8 --application-import-names=pysmurf
```

if we add the flake8-import-order extension in the travis flake8 checks.

## Does this PR break any interface?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jesusvasquez333** [comment]
I will need to carefully check these changes, and test them to make sure nothing breaks. Also, some new orders don't make much sense to me, so I will need to understand why/if there are needed.

**Comment by swh76** [comment]
@jesusvasquez333 oh yea fine to close if you don't want to incorporate.  The only reason why I did it was because it cuts out a bunch of annoying warnings from a linter I was using (pylint) to find some other problems.  I can also just disable the warnings, so whichever you prefer.

**Comment by jesusvasquez333** [comment]
@swh76 not at all. I just need to test the changes before approving this PR. So, I will need some time to tests this.

**Comment by swh76** [comment]
Np @jesusvasquez333 this is like the least urgent PR possible.

**Comment by eyyoung24** [comment]
This may be exactly what Jesus is asking, but... why? Aren't almost all of these imports independent? Is this just code cleanliness? Or is there actually an edge case we're avoiding?

**Comment by swh76** [comment]
Only what I wrote above ; it's just an easy fix to get rid of a bunch of common linting errors.  I presume there is some reason for the pep8 import standards but I don't know it.

**Pull request merged**
