### PR TITLE
Update smurf_util.py

### PR DESCRIPTION
**Pull request by ccffccffcc**
Use list instead of np.array in read_stream_data function. This will speed up the function.

### CODE REVIEW

**Comment by swh76** [comment]
@ccffccffcc none of us recognized your username - are you an SO contributor?

**Comment by eyyoung24** [comment]
Sorry, @ccffccffcc is Feng. I am working with him on this.

**Comment by swh76** [comment]
No problem, thanks @eyyoung24 @ccffccffcc .  Feng, could you please make the title of the PR more informative and resolve the broken checks?

**Comment by swh76** [comment]
Closing, will submit a non-forked PR with the same code changes.

**Pull request closed without merging**
