### PR TITLE
Extract issue references from PR body

### PR DESCRIPTION
**Pull request by slacrherbst**
This change will scan the pull request body for the #123 pattern in an attempt to find references to issues.

### CODE REVIEW

**Comment by jesusvasquez333** [comment]
Issues can also be mentioned in comments in the PR, so I modify the script to look in comments as  well. 
Also, I modified to avoid reporting the same issue number multiple times, if the same issue is mentioned more than once in the PR.

Unfortunately, an issue can also be manually linked to a PR, without mentioning in the description to comments. But I didn't find a way to get those. So, those won't be reported in the release notes.

**Comment by slacrherbst** [comment]
It appears that the Issue list can get reset with each comment.

**Comment by slacrherbst** [comment]
Nevermind I misread.

**Comment by slacrherbst** [comment]
Also it appears that issue and PR numbers are generated from the same pool. At least it appears that way.

**Pull request merged**
