### PR TITLE
docs: pin sphinx version for rtd build

### LINKED ISSUE #701: Readthedocs builds currently broken
Builds on readthedocs are currently broken, and have been for the past 2 months.

I have a fix, so PR incoming.

https://readthedocs.org/projects/pysmurf/builds/15214768/

```
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
loading intersphinx inventory from https://docs.python.org/release/3.6.9/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 20 source files that are out of date
updating environment: 20 added, 0 changed, 0 removed
reading sources... [  5%] client/base

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    Transformer.apply_transforms(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 245, in apply
    apply_source_workaround(n)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysmurf/envs/main/lib/python3.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible
The full traceback has been saved in /tmp/sphinx-err-has4hoow.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

### PR DESCRIPTION
**Pull request by BrianJKoopman**
## Issue
This PR resolves #701.

## Description

This adds a requirements file for the docs builds on readthedocs. In this, we pin the Sphinx version, which resolves the issue seen in #701.

Successful test build here: https://readthedocs.org/projects/pysmurf/builds/15843942/

## Does this PR break any interface?
- [ ] Yes
- [x] No

### Which interface changed?
No change.

### What was the interface before the change
No change.

### What will be the new interface after the change
No change.

### CODE REVIEW

**Review by swh76 — DISMISSED** [review]

**Review by aer7 — APPROVED** [review]

**Comment by aer7** [comment]
Thanks @BrianJKoopman! Preferably could you throw this on top of develop? I modified the rtd file in there already, and need to test it anyway...

**Comment by BrianJKoopman** [comment]
Sorry for all the noise, that took a couple of iterations with the rtd build system to figure out.

I swapped the base branch to 'develop'. The rtd config on 'develop' was failing for a couple of reasons. I ended up back at a config that's very similar to the old one on 'main'.

The build is now passing: https://readthedocs.org/projects/pysmurf/builds/15917517/

**Comment by BrianJKoopman** [comment]
Quick followup. I just noticed the warning that the python.version option is deprecated for build.tools.python, which is what you were using in 'develop'. However, that option was causing a failure on the build system, see: https://readthedocs.org/projects/pysmurf/builds/15917436/

**Review by aer7 — APPROVED** [review]
Ship it

**Pull request merged**
