### PR TITLE
Crate issues and PR templates

### LINKED ISSUE #346: Setup issues and PR templates
This will allow to have consistent information in both issues and PR.

### PR DESCRIPTION
**Pull request by jesusvasquez333**
This PR resolves #346 

This PR will add templates to both issues and PRs. Please find below a preview of the templates, please let me know if you want a different format, or content.

# PRs will have this template:
## Issue
This PR resolves [introduce here issue number(s) or jira ticket(s). If there are no issues for this PR, please first open an issue for it].

## Description

  [Describe what this PR does here]

  ## Does this PR break any interface?
 - [ ] Yes
 - [ ] No

# When opening an issue, you will be able to choose one out of three types of issues, each one with a different template, and the appropriate label will be automatically assigned:

## Describe the bug
 A clear and concise description of what the bug is here.

  ## To Reproduce

  ## Expected behavior

  ## Additional details
 Add any other details about the problem here.

## Additional details
 Add any other details about the feature request here.

### CODE REVIEW

**Comment by eyyoung24** [comment]
Can there be a basic template for the interface change too? Something like "What is the interfaced that changed? What was its functionality before and what is it now?"

**Comment by jesusvasquez333** [comment]
@eyyoung24 Yes, we can make the interface change section of the PR template to look like this:

## Does this PR break any interface?
 - [ ] Yes
 - [ ] No

### Which interface changed?
Describe here what is the interface that changed
### What was the interface before the change
Describe here how was 
### What will be the new interface after the change

**Comment by jesusvasquez333** [comment]
@slacrherbst They will look like this in the PR detials

# Pull Request Details
### Bug fix: trying to set a register to an empty array is not supported
|||
|---:|:---|
|**Author:**|Shawn Henderson <shawn@slac.stanford.edu>|
|**Date:**|Sun Mar 22 09:02:01 2020 -0700|
|**Pull:**|#336 (2 additions, 2 deletions, 1 files changed)|
|**Branch:**|slaclab/issue335|
|**Issues:**|#335|
|**Labels:**|bug, client|

**Notes:**
> ## Issue
> This PR resolves [introduce here issue number(s) or jira ticket(s). If there are no issues for this PR, please first open an issue for it].
> 
> ## Description
> 
> [Describe what this PR does here]
> 
> ## Does this PR break any interface?
> - [ ] Yes
> - [ ] No
> 
> ### Which interface changed?
> [Indicate here what is the interface that changed, preferable with a link to the code where the interface is defiend]
> 
> ### What was the interface before the change
> [Describe here how was the original interface]
> 
> ### What will be the new interface after the change
> [Describe here how is the new interface, and what the difference with the original interface]

-------

**Comment by eyyoung24** [comment]
This looks great. Thanks @jesusvasquez333

**Comment by jesusvasquez333** [comment]
@eyyoung24 Thanks!. I added the modifications to the PR template. 

Can you please re-approve?

**Pull request merged**
