### PR TITLE
feat(core.server_scripts.Common): Set log level and format.

### PR DESCRIPTION
**Pull request by tristpinsm**
## Description

Add a log handler with timestamps to capture the output of the rogue (and other) logs.

This works, but rogue is extremely verbose at the `INFO` level. It might be useful to set a more relaxed level for just the `cryo-det` modules.

## Jira Issue

ESCRYODET-

## Function interfaces that changed

[Indicate here what is the interface that changed, preferably with a link to the code where the interface is defined]

### What was the interface before the change
[Describe here how was the original interface]

### What will be the new interface after the change
[Describe here how is the new interface, and what the difference with the original interface]

### CODE REVIEW

**Review by jlashner — APPROVED** [review]
This looks great! Do you happen to know if warnings are what is already being printed, or if this will introduce new messages into the logs? I am fine with this as long as its not overwhelming, but it may confuse people who are used to looking through smurf-logs to debug.

**Comment by tristpinsm** [comment]
That's a good point. Warning is the default in python, and I haven't seen the level explicitly set in the rogue python code. Looking at the C++ logging it looks like it is set to error by default... So if your impression is that we have been running under that level so far I can change it.

**Comment by jlashner** [comment]
Do you have an example log-file at the warning level that I could look through? I could tell you if that's what we have by default or not.

**Comment by tristpinsm** [comment]
Sure, I can generate that later today

**Comment by tristpinsm** [comment]
I can't run with the full `sodetlib` software stack right now because of the firmware that is deployed on our test system, but just running SMuRF through `setup` to `find_freq` I don't see any warning messages.

**Comment by tristpinsm** [comment]
@swh76 with your stamp of approval I'll merge this and wrap it into the `pysmurf` release

**Review by swh76 — APPROVED** [review]

**Pull request merged**
